Homework 6: from a monolith to microservices
GenesisEducationKyiv/hw1-se-school_2022-code-review-Dichik pull request #21
Opened 2022-09-26 16:37 UTC by Dichik

2022-09-30 14:39 UTC, Valmark-de-Valera requested changes
General cool, just recommend add cache service and make server settings in .env file (environment variables can be useful with docker as example)

2022-09-30 14:39 UTC, Valmark-de-Valera commented on rate-service/src/service/chain/coinbaseRate.service.ts
> +                console.log('There is no another provider... (')
I recommend you to use custom logger like "winston". It is not necessary for now, just keep in mind

2022-09-30 14:39 UTC, Valmark-de-Valera commented on rate-service/src/service/rate.service.ts
> +            Date.now() - this.lastFetchingTime < this.CACHING_TIME &&
Better solution for this will create own or use custom (Node Cache as example) cache service. You can make own CacheService class or use existing solution. You can set TTL as option to custom cache services

2022-09-30 14:39 UTC, Valmark-de-Valera commented on subscription-service/src/app.ts
> +    private port = 9081
I recommend you to make server settings (Like "Host" and "Port") as environment variables

2022-10-02 14:13 UTC, mykolastepanenko approved these changes
Ти переробив на мікросервісну архітектуру. Все ок). Ставлю approve

2022-10-02 17:28 UTC, Dichik commented on rate-service/src/service/chain/coinbaseRate.service.ts
> +                console.log('There is no another provider... (')
Created issue and going to fix in master [link](https://github.com/GenesisEducationKyiv/hw1-se-school_2022-code-review-Dichik/issues/23)

2022-10-02 17:33 UTC, Dichik commented on subscription-service/src/app.ts
> +    private port = 9081
Fixed in [commit](https://github.com/GenesisEducationKyiv/hw1-se-school_2022-code-review-Dichik/pull/21/commits/5e2d6fda648e6c5d20d68ff7c7c2cc0dea66512d)

2022-10-02 17:42 UTC, Dichik commented on rate-service/src/service/rate.service.ts
> +            Date.now() - this.lastFetchingTime < this.CACHING_TIME &&
Fixed in [commit](https://github.com/GenesisEducationKyiv/hw1-se-school_2022-code-review-Dichik/pull/21/commits/3547b0eaecc2cade79287203a5610999f79e9cc5)

2022-10-03 11:46 UTC, merged